[nats]
broker-url = "127.0.0.1"
broker-port = 4222
username = ""
password = ""

[tcp]
enabled = true
host = "127.0.0.1"
port = 3333

[http]
enabled = true
host = "127.0.0.1"
port = 7071

[discovery]
enabled = true

[rotator]
type = "yaesu"
name = "myRotator"
portname = "COM3"
baudrate = 9600
has-azimuth = true
has-elevation = true
pollingrate = "5s"
azimuth-min = 0
azimuth-max = 360
azimuth-stop = 0
elevation-min = 0
elevation-max = 180
