language: go
dist: xenial
sudo: true

matrix:
  include:
  - os: linux
    env:
    - GIMME_OS=linux
      GIMME_ARCH=amd64
      HOST_OS=linux
    go: "1.11"
  - os: linux
    env:
    - GIMME_OS=linux
    - GIMME_ARCH=386
    - HOST_OS=linux
    go: "1.11"
  - os: linux
    env:
    - GIMME_OS=linux
    - GIMME_ARCH=arm
    - HOST_OS=linux
    go: "1.11"
  # - os: linux  #temporarily removed since hashicorp/go.net doesn't compile
  #   env:
  #   - GIMME_OS=linux
  #   - GIMME_ARCH=arm64
  #   - HOST_OS=linux
  #   go: 1.9
  - os: linux
    env:
    - GIMME_OS=windows
    - GIMME_ARCH=amd64
    - HOST_OS=linux
    go: "1.11"
  - os: linux
    env:
    - GIMME_OS=windows
    - GIMME_ARCH=386
    - HOST_OS=linux
    go: "1.10"
  - os: osx
    env:
    - GIMME_OS=darwin
    - GIMME_ARCH=amd64
    - HOST_OS=darwin
    go: "1.11"

before_install:
- git fetch --tags
- GOARCH=amd64 GOOS=$HOST_OS go get golang.org/x/tools/cmd/stringer
- GOARCH=amd64 GOOS=$HOST_OS go get github.com/mattn/goveralls
- GOARCH=amd64 GOOS=$HOST_OS go get github.com/GeertJohan/go.rice/rice
script:
- GOARCH=$GIMME_ARCH GOOS=$GIMME_OS go get ./...
- GOARCH=$GIMME_ARCH GOOS=$GIMME_OS ./ci/test.sh
- GOARCH=amd64 GOOS=$HOST_OS make generate
- GOARCH=$GIMME_ARCH GOOS=$GIMME_OS make dist
# - file remoteRotator
before_deploy:
- ./ci/pack.sh
deploy:
  provider: releases
  api_key:
    secure: BWX1PUIiHuie4Db0FNmQANqA9pHwyzXnJCQ7GQRydnZ3jEf3oHABvuBvXtYCjf7cMvdmG81CLNtQXkPqpDfC4YW/r1LDbK1mN2YT+X3KIs+Qwhi7Y1yrNqLQtjj4gofE0rBt7jSTjxIZn9NN/Zx0iPv6LLIRWLWZ2SSdIKNIqAHFz4CTcdZflmgQKtjEKf3gtdi57oVC/NsObadmil5ojFBnX/5mG2ZVUsST56YlUrxdO8HOunsQyxuip84Gm6KgxdJTy4m74DhdG6odqKC4ifnKCTQ6+/MX0vLJI30WttSsDqBbcdUTt6/dlMD8Lb8RDr/2b9kqYAkUt0xEUdmWJropk93zPTAPEAFeAIg2QTCMGfUdb9YChLOw6yCT/LIQcBmkQ8iQMfUZWvJP1IKFNWfu3SBh4CnuKSfwdOzXWOMl+/jBJYUHZo/pVE+R7vBKxTMGJMaxM1hFSOrJBiGi0zezh+4IFGAabLtmvCOPHllKSi5Sn7XuqQz4xbVGcFlFG6uCrAL1JRPQPD4CHy1xpRhZCIlrHXQMeqBbZSrjYcszSTbAjagwWcqR1veoqkhaeNL+VeQ1QKfeHM1X4bbnELeQsLZTSQ6GwJHW7xpsx1AKPFu+jJqaW9hMFkLnlv0gcYA+iHM+HPsubEPvFkP0R5vrpl+kwybx0zJJ6hSuMPU=
  file_glob: true
  file: remoteRotator-v$TRAVIS_TAG-$GIMME_OS-$GIMME_ARCH.*
  skip_cleanup: true
  on:
    repo: dh1tw/remoteRotator
    tags: true
    draft: true
    go: 1.9