// Code generated by "stringer -type=Event"; DO NOT EDIT.

package rotator

import "fmt"

const _Event_name = "AzimuthElevation"

var _Event_index = [...]uint8{0, 7, 16}

func (i Event) String() string {
	if i < 0 || i >= Event(len(_Event_index)-1) {
		return fmt.Sprintf("Event(%d)", i)
	}
	return _Event_name[_Event_index[i]:_Event_index[i+1]]
}
